# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['dcs_viewer\\app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('dcs_platform', 'dcs_platform'),
        ('dcs_viewer/param_groups.json', 'dcs_viewer'),
        ('dcs_config.json', '.'),
        ('dcs_viewer/rules_opening.html', 'dcs_viewer'),
        ('dcs_viewer/rules_plugging.html', 'dcs_viewer'),
        ('dcs_viewer/knowledge_base.html', 'dcs_viewer'),
        ('dcs_viewer/analysis_new.html', 'dcs_viewer'),
        ('dcs_viewer/detect_config.html', 'dcs_viewer'),
        ('dcs_viewer/variable_config.html', 'dcs_viewer'),
        ('dcs_viewer/welcome.html', 'dcs_viewer'),
        # === 模板文件 ===
        ('dcs_viewer/templates/index.html', 'dcs_viewer/templates'),
        ('dcs_viewer/templates/login.html', 'dcs_viewer/templates'),
        ('dcs_viewer/templates/realtime.html', 'dcs_viewer/templates'),
        ('dcs_viewer/templates/trend.html', 'dcs_viewer/templates'),
        ('dcs_viewer/templates/analysis.html', 'dcs_viewer/templates'),
        ('dcs_viewer/templates/labeling.html', 'dcs_viewer/templates'),
        ('dcs_viewer/templates/report.html', 'dcs_viewer/templates'),
        ('dcs_viewer/templates/settings.html', 'dcs_viewer/templates'),
        # === 静态资源 ===
        ('dcs_viewer/static/lib/jquery-3.7.1.min.js', 'dcs_viewer/static/lib'),
        ('dcs_viewer/static/lib/jquery.dataTables.min.js', 'dcs_viewer/static/lib'),
        ('dcs_viewer/static/lib/jquery.dataTables.min.css', 'dcs_viewer/static/lib'),
        ('dcs_viewer/static/lib/uPlot.iife.min.js', 'dcs_viewer/static/lib'),
        ('dcs_viewer/static/lib/uPlot.min.css', 'dcs_viewer/static/lib'),
        ('dcs_viewer/static/lib/chart.umd.min.js', 'dcs_viewer/static/lib'),
    ],
    hiddenimports=['flask_compress', 'xlsxwriter', 'influxdb_client', 'waitress',
                   'sqlite3', '_sqlite3',
                   'dcs_platform', 'dcs_platform.core', 'dcs_platform.core.config',
                   'dcs_platform.core.influx_client', 'dcs_platform.core.db',
                   'dcs_platform.services', 'dcs_platform.services.group_service',
                   'dcs_platform.services.query_service',
                   'dcs_platform.services.cycle_detector_plugging',
                   'dcs_platform.services.cycle_detector_opening',
                   'dcs_platform.services.feature_engineering',
                   'dcs_platform.services.feature_quality',
                   'dcs_platform.services.report_generator',
                   'dcs_platform.services.rule_engine',
                   'dcs_platform.services.model_trainer',
                   'dcs_platform.services.dynamic_detector',
                   'dcs_platform.services.self_tuning',
                   'dcs_platform.services.analysis',
                   'dcs_platform.services.analysis.state_identifier',
                   'dcs_platform.services.analysis.process_analyzer',
                   'dcs_platform.services.analysis.pressure_position_analyzer',
                   'dcs_platform.services.analysis.health_analyzer',
                   'dcs_platform.services.analysis.side_comparison',
                   'dcs_platform.routes',
                   'dcs_platform.routes.analysis_api',
                   'dcs_platform.routes.labeling_api',
                   'dcs_platform.routes.rules_api',
                   'dcs_platform.routes.knowledge_api',
                   'dcs_platform.routes.training_api'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['pandas', 'matplotlib', 'openpyxl', 'lxml', 'PIL', 'tkinter', 'scipy', 'pyarrow'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='DCSViewer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
